//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18449
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Sram.Configuration
{
	public class Config
	{
		public GameTimeConfig GameTimeConfig {get; private set;}
		public KeyConfig KeyConfig { get; private set; }
		public PlanetConfig PlanetConfig { get; private set; }
		public InventoryConfig InventoryConfig { get; private set; }
		public PlayerConfig PlayerConfig { get; private set; }
		public PlayerBaseConfig PlayerBaseConfig { get; private set; }
		public SpaceSuitConfig SpaceSuitConfig { get; private set; }
		public SpaceCapsuleManagerConfig SpaceCapsuleManagerConfig { get; private set; }
		public TerrainGeneratorConfig TerrainGeneratorConfig { get; private set; }

		public bool ShowHideFps;
		public int MaxLogLinesCount{ get; private set; }

		private Config ()
		{
			this.ShowHideFps = false;
			this.MaxLogLinesCount = 8;

			this.GameTimeConfig = GameTimeConfig.GetConfig ();
			this.KeyConfig = KeyConfig.GetConfig ();
			this.PlanetConfig = PlanetConfig.GetPlanetConfig ();
			this.PlayerConfig = PlayerConfig.GetConfig (this.GameTimeConfig.TimeMultiplicator);
			this.PlayerBaseConfig = PlayerBaseConfig.GetPlayerBaseConfig ();
			this.InventoryConfig = InventoryConfig.GetConfig ();
			this.SpaceSuitConfig = SpaceSuitConfig.GetConfig (this.GameTimeConfig.TimeMultiplicator);
			this.SpaceCapsuleManagerConfig = SpaceCapsuleManagerConfig.GetConfig ();
			this.TerrainGeneratorConfig = TerrainGeneratorConfig.GetConfig ();
		}

		public static Config GetConfig()
		{
			return new Config();
		}
	}
}

