//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18449
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Sram.Configuration
{
	public class KeyConfig
	{
		public KeyCode PauseGame { get; private set; }
		public KeyCode ShowHideFps { get; private set; }

		public KeyCode TimeAcceleratorLess { get; private set; }
		public KeyCode TimeAcceleratorPlus { get; private set; }

		public KeyCode InventoryOpener { get; private set; }

		public KeyCode SpaceCapsuleLauncher { get; private set; }

		public KeyCode ObjectInteractionKey { get; private set; }

		public KeyCode TorchligthOnOff { get; private set; }


		public static KeyConfig GetConfig()
		{
			return new KeyConfig () {
				PauseGame= KeyCode.Escape,
				ObjectInteractionKey=KeyCode.F,
				ShowHideFps = KeyCode.F1,
				SpaceCapsuleLauncher=KeyCode.F2,
				InventoryOpener = KeyCode.I,
				TimeAcceleratorLess = KeyCode.PageDown,
				TimeAcceleratorPlus = KeyCode.PageUp,
				TorchligthOnOff=KeyCode.X,
			};
		}

	}
}

